spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource: #数据源
      names: m1,m2
      m1: #基础数据库信息配置，参数同原生一致
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/order_db_1?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true
        username: root
        password: root@1763
        max-total: 100
        initialSize:  10
        minIdle:  10
        maxActive:  100
        maxWait:  60000
        timeBetweenEvictionRunsMillis:  60000
        minEvictableIdleTimeMillis:  300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle:  true
        testOnBorrow:  false
        testOnReturn:  false
        poolPreparedStatements:  true
        maxPoolPreparedStatementPerConnectionSize:  20
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/order_db_2?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true
        username: root
        password: root@1763
        max-total: 100
        initialSize:  10
        minIdle:  10
        maxActive:  100
        maxWait:  60000
        timeBetweenEvictionRunsMillis:  60000
        minEvictableIdleTimeMillis:  300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle:  true
        testOnBorrow:  false
        testOnReturn:  false
        poolPreparedStatements:  true
        maxPoolPreparedStatementPerConnectionSize:  20
    sharding:
      tables:
        t_user:
          actual-data-nodes: m$->{1..2}.t_user #t_user分库分表策略
          table-strategy: # t_user分片策略
            inline:
              sharding-column: user_id
              algorithm-expression: t_user
          database-strategy: # t_user分库策略
            inline:
              sharding-column: user_id
              algorithm-expression: m$->{user_id % 2 + 1}
    props:
      sql:
        show: true # 打开sql输出日志
      query:
        with:
          cipher:
            column: true